name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_HELM_REPO: ${{ vars.NEXUS_HELM_REPO }}
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: ${{ vars.SAUSAGE_STORE_NAMESPACE }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  APP_VERSION: 1.0.0
  #VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
  CHART_PATH: ./sausage-store-chart

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/sausage-backend:${{ env.APP_VERSION }}
            build-args: |
              VERSION=${{ env.APP_VERSION }}
        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/sausage-frontend:${{ env.APP_VERSION }}
        - name: Push Backend-report to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend-report/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/sausage-backend-report:${{ env.APP_VERSION }}

  # Упаковываем helm-чарт и пушим его в Nexus
  add_helm_chart_to_nexus:
      name: Add Helm Chart To Nexus
      runs-on: ubuntu-latest
      #needs: build_and_push_to_docker_hub
      outputs:
        chart-name: ${{ steps.chart.outputs.name }}
        chart-version: ${{ steps.chart.outputs.version }}
        chart-pkg: ${{ steps.chart.outputs.pkg }}

      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Install Helm
            uses: azure/setup-helm@v3
            with:
              version: 'latest'

          - name: Package Helm Chart
            run: |
              helm dependency update ${{ env.CHART_PATH }}
              helm package ${{ env.CHART_PATH }}
              echo "CHART_PKG=$(ls *.tgz)" >> $GITHUB_ENV
          
          - name: Prepare output variables
            id: chart
            run: |
              echo $CHART_PKG
              CHART_NAME=$(helm show chart $CHART_PKG | grep '^name:' | awk '{print $2}')
              CHART_VERSION=$(helm show chart $CHART_PKG | grep '^version:' | awk '{print $2}')
              echo "pkg=$CHART_PKG" >> $GITHUB_OUTPUT
              echo "name=$CHART_NAME" >> $GITHUB_OUTPUT
              echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT

          - name: Upload Chart to Nexus Repository
            run: |
              curl -u ${{ env.NEXUS_HELM_REPO_USER }}:${{ env.NEXUS_HELM_REPO_PASSWORD }} \
                --upload-file $CHART_PKG \
                ${{ env.NEXUS_HELM_REPO }}/$CHART_PKG
              echo "Helm chart uploaded to Nexus repository: ${{ env.NEXUS_HELM_REPO }}/$CHART_PKG"

  # Деплоим приложения в кластер Kubernetes с помощью helm-чарт
  deploy_helm_chart_to_kubernetes:
      name: Deploy Helm Chart To Kubernetes
      runs-on: ubuntu-latest
      needs: add_helm_chart_to_nexus

      steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ env.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Add Nexus Helm Repository
        run: |
          helm repo add nexus ${{ env.NEXUS_HELM_REPO }} \
            --username ${{ env.NEXUS_HELM_REPO_USER }} \
            --password ${{ env.NEXUS_HELM_REPO_PASSWORD }}
          helm repo update

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install sausage \
            nexus/${{ needs.add_helm_chart_to_nexus.outputs.chart-name }} \
            --version ${{ needs.add_helm_chart_to_nexus.outputs.chart-version }} \
            --namespace ${{ env.SAUSAGE_STORE_NAMESPACE }} \
            --debug \
            --wait \
            --timeout 10m

      - name: Verify Deployment
        run: |
          kubectl get all -n ${{ env.SAUSAGE_STORE_NAMESPACE }}
